numerically stable matrix exponentiation, fix sum for vlattice

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -1,5 +1,6 @@
 #!/bin/bash
 runner=$1
+fail=0
 if [[ "$runner" != "" ]];
 then
     echo "Using runner = $runner"
@@ -29,6 +30,7 @@ then
 else
     echo "ERR ($elapsed s)"
     cat ${LOG}
+    fail=$((fail+1))
 fi
 
 done
@@ -38,4 +40,10 @@ then
     rm -f ${LOG}
 fi
 
-
+if ((fail != 0))
+then
+    echo "$fail tests failed"
+    exit 1
+else
+    echo "All tests successful"
+fi
